apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: nexus-3
spec:
  type: NodePort
  selector:
    app: setup
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 32000
